server:
  error:
    whitelabel:
      enabled: false
  tomcat:
    accesslog:
      enabled: true
  port: 8080
logging:
  level:
    ROOT: info
#    org.springframework.security: info
    nl.appsource: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

cardserver:
  couchbase:
    connection-string: couchbase://192.168.1.86
    username: root
    password: killer
    bucket-name: cardserver
  auth:
    jwt-secret: NGfSZOnfZNETMKCaUd9dNhLzTiur4nwxYALP39JGRm4s3hcQIHQI65wQvqdwn8C8


