server:
  port: 8080
logging:
  level:
    ROOT: info
#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://accounts.google.com
#          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

cardserver:
  couchbase:
    connection-string: couchbase://couchbase.couchbase
    username: root
    password: killer
    bucket-name: cardserver



