server:
  error:
    whitelabel:
      enabled: false
  tomcat:
    accesslog:
      enabled: true
  port: 8080
logging:
  level:
    ROOT: info
    nl.appsource: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
cardserver:
  auth:
    jwt-ed25519-secret: '{"kty":"OKP","d":"HIC-_XuJgk2q_esYxsvYhe1sGp7d6iA04N2-IXUGPTg","use":"sig","crv":"Ed25519","kid":"citest-8-key-A-745992","x":"4iTqtvdXsVs6FjUU39rDPCYVrIhpSO9os3McyffAOHE","alg":"EdDSA"}'
