server:
  error:
    whitelabel:
      enabled: false
  tomcat:
    accesslog:
      enabled: true
  port: 8080
logging:
  level:
    ROOT: info
    nl.appsource: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
cardserver:
  auth:
    jwt-ed25519-secret: eyJrdHkiOiJPS1AiLCJkIjoiSElDLV9YdUpnazJxX2VzWXhzdlloZTFzR3A3ZDZpQTA0TjItSVhVR1BUZyIsInVzZSI6InNpZyIsImNydiI6IkVkMjU1MTkiLCJraWQiOiJjaXRlc3QtOC1rZXktQS03NDU5OTIiLCJ4IjoiNGlUcXR2ZFhzVnM2RmpVVTM5ckRQQ1lWcklocFNPOW9zM01jeWZmQU9IRSIsImFsZyI6IkVkRFNBIn0K
