server:
  error:
    whitelabel:
      enabled: false
  tomcat:
    accesslog:
      enabled: true
  port: 8080
logging:
  level:
    ROOT: info
    nl.appsource: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
#  couchbase:
#    connection-string: couchbase://localhost/cardserver
#    username: root
cardserver:
  auth:
    jwt-secret: killer
