server:
  error:
    whitelabel:
      enabled: false
  tomcat:
    accesslog:
      enabled: true
  port: 8080
logging:
  level:
    ROOT: info
#    org.springframework.security: info
    nl.appsource: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

cardserver:
  couchbase:
    connection-string: couchbase://192.168.1.86
    username: root
    password: killer
    bucket-name: cardserver
  auth:
    jwt-ed25519-secret: '{"kty":"OKP","d":"VxMCmykLHU9kLwP000nlTbhf6vvVwICSGgz7LVN5RPM","use":"sig","crv":"Ed25519","kid":"dev-8-key-A-745992","x":"fcYRCahGWcrEWOOjQHT4CA9sAUjMm4Nvc__3n0hmwS4","alg":"EdDSA"}'

