spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  couchbase:
    connection-string: couchbase://couchbase-0.couchbase-main.couchbase.svc.cluster.local.,couchbase-1.couchbase-main.couchbase.svc.cluster.local.,couchbase-2.couchbase-main.couchbase.svc.cluster.local.
    username: root
    password: killer
  data:
    couchbase:
      bucket-name: cardserver


logging:
  level:
    ROOT: warn
    nl.appsource: debug
