spring:
  data:
    redis:
      host: redis-stack.redis-stack.svc.cluster.local
      port: 6379
  boot:
    admin:
      client:
        url: http://cardserver-admin.cardserver:8085/admin
        instance:
          service-base-url: http://cardserver-aiplayer.cardserver:8084
          management-base-url: http://cardserver-aiplayer.cardserver:9084
cardserver:
  couchbase:
    connection-string: couchbase://couchbase.couchbase.svc.cluster.local
    username: root
    password: killer
    bucket-name: cardserver
logging:
  level:
    ROOT: info
    nl.appsource: debug
