spring:
  data:
    redis:
      host: redis-stack.redis-stack.svc.cluster.local
      port: 6379
  boot:
    admin:
      client:
        url: http://cardserver-admin.cardserver:8085/admin
        instance:
          service-base-url: http://cardserver-api.cardserver:8080
          management-base-url: http://cardserver-api.cardserver:9080
server:
  port: 8080
logging:
  level:
    ROOT: info
    com:
      couchbase: warn

cardserver:
  couchbase:
    connection-string: couchbase://couchbase.couchbase.svc.cluster.local
    username: root
    password: killer
    bucket-name: cardserver

