server:
  port: 8080
  shutdown: graceful
logging:
  level:
    ROOT: info
#    org.springframework: trace
    nl.appsource: debug
spring:
  web:
    error:
      whitelabel:
        enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.impl.nl/realms/klaversjassen

cardserver:
  couchbase:
    connection-string: couchbase://192.168.1.86
    username: root
    password: killer
    bucket-name: cardserver
