spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.data.redis.autoconfigure.DataRedisReactiveAutoConfiguration
      - org.springframework.boot.data.redis.autoconfigure.DataRedisAutoConfiguration
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://auth.impl.nl/realms/klaversjassen/protocol/openid-connect/certs
logging:
  level:
    ROOT: info
    nl.appsource: debug
