spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.impl.nl/realms/klaversjassen
server:
  port: 8080

logging:
  level:
    ROOT: info
    com:
      couchbase: warn

cardserver:
  couchbase:
    connection-string: couchbase://couchbase.couchbase.svc.cluster.local
    username: root
    password: killer
    bucket-name: cardserver
