server:
  port: 8080
  shutdown: graceful
logging:
  level:
    ROOT: info
#    org.springframework: trace
    nl.appsource: debug
spring:
  web:
    error:
      whitelabel:
        enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.impl.nl/realms/klaversjassen
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  couchbase:
    connection-string: couchbase://couchbase-0.couchbase-main.couchbase.svc.cluster.local.,couchbase://couchbase-1.couchbase-main.couchbase.svc.cluster.local.,couchbase://couchbase-2.couchbase-main.couchbase.svc.cluster.local.
    username: root
    password: killer
  data:
    couchbase:
      bucket-name: cardserver
