server:
  port: 8085
spring:
  security:
    user:
      name: root
      password: killer
  cloud:
    discovery:
      enabled: true
    kubernetes:
      discovery:
        all-namespaces: false
#        primary-port-name: http
        metadata:
          add-annotations: true
management:
  endpoint:
    env:
      show-values: always
    info:
      access: read_only
    health:
      access: read_only
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 9085
    ssl:
      enabled: false
    add-application-context-header: true
