spring:
  data:
    redis:
#      host: 10.103.71.147
      host: 127.0.0.1
      port: 6379
cardserver:
  couchbase:
    connection-string: couchbase://192.168.1.86
    username: root
    password: killer
    bucket-name: cardserver


