spring:
  data:
    redis:
      host: redis-stack.redis-stack.svc.cluster.local
      port: 6379
server:
  port: 8080
logging:
  level:
    ROOT: info
    com:
      couchbase: warn

cardserver:
  couchbase:
    connection-string: couchbase://couchbase.couchbase
    username: root
    password: killer
    bucket-name: cardserver



