server:
  port: 8080
  shutdown: graceful
logging:
  level:
    ROOT: info
#    org.springframework: trace
    nl.appsource: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  web:
    error:
      whitelabel:
        enabled: false
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://accounts.google.com
#          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

cardserver:
  couchbase:
    connection-string: couchbase://192.168.1.86
    username: root
    password: killer
    bucket-name: cardserver
  auth:
    jwt-es512-secret: '{"kty":"EC","d":"ALjr1TqvNbOR_HxHwJlBnJ5MybU1Dz8Gbu4arEoJIrJ76eVdpQTpBwAmAu7ODhW39Lu-iZqp2qFE_TER6Lb7ZyH6","crv":"P-521","kid":"es512-key-1","x":"ACtrVUN1XroGXBxVpnuQpKijmIrEIv0-i8ySfR_Kdj9mWzcz75ztTVmEC_llfZLXYavNcYoo4hzPLRV554oBclmk","y":"AU3GODl2efwvg5clz5Wen3Qrv6XHwcaVUgJaXrxmItVzBPjsEbJR4j8HC4ho2-8o1NRhh9x0zhqUjWyW5to5ydpf"}'
