server:
  compression:
    enabled: true
  forward-headers-strategy: framework
  shutdown: graceful
  port: 8080
logging:
  level:
    ROOT: info
    nl.appsource: info
spring:
  lifecycle:
    timeout-per-shutdown-phase: 2s
  main:
    web-application-type: reactive
  application:
    name: Stream
  jackson:
    default-property-inclusion: non_absent
    time-zone: Europe/Amsterdam
  output:
    ansi:
      enabled: ALWAYS
  web:
    resources:
      cache:
        cachecontrol:
          no-store: true
          no-cache: true
          max-age: 0
management:
  endpoint:
    env:
      show-values: always
    info:
      access: read_only
    health:
      access: read_only
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: 'health,info,env'
  server:
    port: 9080
    ssl:
      enabled: false
    add-application-context-header: true
