spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://api.klaversjassen.nl"
cardserver:
  couchbase:
    connection-string: couchbase://192.168.1.86
    username: root
    password: killer
    bucket-name: cardserver

logging:
  level:
    ROOT: info
    nl.appsource: debug
