spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.impl.nl/realms/klaversjassen
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    consumer:
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
cardserver:
  couchbase:
    connection-string: couchbase://192.168.1.86
    username: root
    password: killer
    bucket-name: cardserver

logging:
  level:
    ROOT: info
    nl.appsource: debug
    org.springframework.security: trace
