cardserver:
  couchbase:
    connection-string: couchbase://couchbase.couchbase.svc.cluster.local
    username: root
    password: killer
    bucket-name: cardserver
logging:
  level:
    ROOT: warn
    nl.appsource: debug
