openapi: "3.0.4"
info:
  title: Klavers JAssen
  description: Klavers JAssen
  version: 1.0.0
servers:
  - url: 'https://www.klaversjassen.nl/api/v1'
    description: Klavers Jassen

paths:
  /whoami:
    get:
      operationId: whoami
      responses:
        "200":
          $ref: "#/components/responses/LoginResponse"
      tags:
        - Login
  /games:
    get:
      operationId: getGames
      responses:
        "200":
          $ref: "#/components/responses/GamesResponse"
      tags:
        - Game
  /games/{gameId}:
    get:
      operationId: getGame
      parameters:
        - $ref: "#/components/parameters/gameId"
      responses:
        "200":
          $ref: "#/components/responses/GameResponse"
      tags:
        - Game
  /users/{userId}:
    get:
      operationId: getUser
      parameters:
        - $ref: "#/components/parameters/userId"
      responses:
        "200":
          $ref: "#/components/responses/UserResponse"
      tags:
        - Game
components:
  schemas:
    loginResponse:
      $ref: "./user.yaml#/components/schemas/User"
  parameters:
    gameId:
      name: gameId
      in: path
      schema:
        type: string
      required: true
    userId:
      name: userId
      in: path
      schema:
        type: string
      required: true
  securitySchemes:
    openId:
      type: openIdConnect
      scheme: bearer
      bearerFormat: JWT
      openIdConnectUrl: https://accounts.google.com/.well-known/openid-configuration
  responses:
    GameResponse:
      description: fetch a game
      content:
        application/json:
          schema:
            $ref: "./game.yaml#/components/schemas/Game"
    UserResponse:
      description: fetch a game
      content:
        application/json:
          schema:
            $ref: "./user.yaml#/components/schemas/User"
    GamesResponse:
      description: fetch all games
      content:
        application/json:
          schema:
            type: array
            items:
              type: string
            uniqueItems: true
    LoginResponse:
      description: login response
      content:
        application/json:
          schema:
            $ref: "./user.yaml#/components/schemas/User"
security:
  - bearerAuth:
      - openid
      - profile
      - email
