name: CardServer

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:

  build:
    #runs-on: buildjet-2vcpu-ubuntu-2204-arm
    runs-on: ubuntu-22.04-arm

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0

      - name: Login to GHCR
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          registry: ghcr.io/bhuism/cardserver
          username: bhuism
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5
        with:
          images: ghcr.io/bhuism/cardserver

      - name: Setup Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          distribution: 'liberica'
          java-version: '21'
          cache: 'maven'

      - name: Build image
        run: |
          mvn -ntp -B -Dspring-boot.build-image.imageName=ghcr.io/bhuism/cardserver:latest clean install org.apache.maven.plugins:maven-checkstyle-plugin:check com.github.spotbugs:spotbugs-maven-plugin:check spring-boot:build-image

      - name: Push
        id: push
        if: success() && github.event_name != 'pull_request'
        run: |
          docker push ghcr.io/bhuism/cardserver:latest

  rollout-restart:
    name: Rollout Restart
    needs: build
    if: github.event_name == 'push'
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    steps:

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubectl"
          chmod +x ./kubectl

      - name: Set Kubernetes Context
        uses: Azure/k8s-set-context@212a19233d93f03eceaac31ae5a1d1acf650b6ef # v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Rollout Restart Deployment
        run: ./kubectl -n cardserver rollout restart deployment cardserver
