name: CardServer

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  test:
    name: Test & Code Quality
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0

      - name: Setup  Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          java-version: '21'
          distribution: 'liberica'
          cache: maven

      - name: Test with Maven
        run: mvn -ntp -B clean install org.apache.maven.plugins:maven-checkstyle-plugin:check com.github.spotbugs:spotbugs-maven-plugin:check
#        run: mvn -ntp -B clean verify org.apache.maven.plugins:maven-checkstyle-plugin:check com.github.spotbugs:spotbugs-maven-plugin:check

  build:
    strategy:
      fail-fast: true
      matrix:
        platform: [amd64, arm64]
        include:
          - platform: amd64
            runner: ubuntu-latest
            javaarch: x64
          - platform: arm64
            runner: buildjet-4vcpu-ubuntu-2204-arm
            javaarch: aarch64
    runs-on: ${{ matrix.runner }}

    needs:
      - test

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0

      - name: Login to GHCR
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          registry: ghcr.io/bhuism/cardserver
          username: bhuism
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5
        with:
          images: ghcr.io/bhuism/cardserver

      - name: Setup Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          distribution: 'liberica'
          architecture: ${{ matrix.javaarch }}
          java-version: '21'
          cache: 'maven'

      - name: Buid and publish image via spring build-image
        if: github.event_name != 'pull_request'
        run: |
          mvn -ntp -B -DskipTests clean spring-boot:build-image -Dspring-boot.build-image.imagePlatform=linux/${{ matrix.platform }} -Dspring-boot.build-image.imageName=ghcr.io/bhuism/cardserver:latest-${{ matrix.platform }}

      - name: Push
        run: |
          docker push ghcr.io/bhuism/cardserver:latest-${{ matrix.platform }}

  manifest-and-push:
    name: Manifest and Push
    runs-on: ubuntu-latest
    needs: build
    if: success() && github.event_name != 'pull_request'

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Login to GHCR
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          registry: ghcr.io/bhuism/cardserver
          username: bhuism
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: merge containers and push
        run: |
          docker manifest create ghcr.io/bhuism/cardserver:latest \
            ghcr.io/bhuism/cardserver:latest-amd64 ghcr.io/bhuism/cardserver:latest-arm64
          docker manifest push ghcr.io/bhuism/cardserver:latest

      - name: remove intermediate containers
        run: |
          docker rmi ghcr.io/bhuism/cardserver:latest-amd64 ghcr.io/bhuism/cardserver:latest-arm64

  rollout-restart:
    needs: manifest-and-push
    runs-on: ubuntu-latest
    name: Rollout Restart
    steps:
      - name: Kubernetes context
        uses: Azure/k8s-set-context@212a19233d93f03eceaac31ae5a1d1acf650b6ef # v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Rollout Restart
        run: kubectl -n cardserver rollout restart deployment cardserver
