name: CardServer

on:
  push:
    branches: [ "development", "sinks-many" ]
  pull_request:
    branches: [ "development" ]

jobs:

  build:
    runs-on: ubuntu-22.04-arm

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Login to GHCR
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io/bhuism/cardserver
          username: bhuism
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          images: |
            ghcr.io/bhuism/cardserver
            ghcr.io/bhuism/couchbase2redis
            ghcr.io/bhuism/stream
            ghcr.io/bhuism/gameengine

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'

      - name: Build image
        run: |
          mvn -ntp -T 1C clean install org.apache.maven.plugins:maven-checkstyle-plugin:check com.github.spotbugs:spotbugs-maven-plugin:check spring-boot:build-image

      - name: Push
        id: push
        if: success() && github.event_name != 'pull_request'
        run: |
          docker push ghcr.io/bhuism/stream:latest
          docker push ghcr.io/bhuism/couchbase2redis:latest
          docker push ghcr.io/bhuism/cardserver:latest
          docker push ghcr.io/bhuism/gameengine:latest

  rollout-restart:
    name: Rollout Restart
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Rollout Restart Deployments
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: -n cardserver rollout restart deployment cardserver-cardservercontroller cardserver-couchbase2rediscontroller cardserver-streamcontroller cardserver-gameengine
